---
title: "R Notebook"
output: html_notebook
---

```{r}
suppressMessages(library(tidyverse))
suppressMessages(library(lubridate))
```

```{r}
url_cran <- "http://cran.r-project.org/web/packages/available_packages_by_date.html"
file_html <- read_file(url_cran)
str_count(file_html,"\\n")
```

<tr> <th> Date </th> <th> Package </th> <th> Title </th> </tr>\n<tr> <td> 2019-03-26 </td> <td> <a href=\"../../web/packages/BIOMASS/index.html\">BIOMASS</a> </td> <td> Estimating Aboveground Biomass and Its Uncertainty in Tropical\nForests </td> </tr>

```{r}
file_csv <- file_html %>%
  str_extract_all("<tr>.*?</tr>") %>%
  first %>%
  str_remove_all("</?tr>") %>%
  str_remove_all("</t[hd]>") %>%
  str_squish() %>%
  str_remove_all("^<t[hd]> ") %>%
  str_remove_all("<a href=.*?>") %>%
  str_remove_all("</a>") %>%
  str_remove_all(fixed('"')) %>%
  str_replace_all(" <t[dh]> ","|")
```

```{r}
df_cran <- file_csv %>% read_delim(delim=fixed("|"))
```

```{r}
df_cran %>%
  mutate(ym=sprintf("%s-%02d-01",year(Date),month(Date))) %>%
  count(ym) %>%
  arrange(ym) %>%
  mutate(ym=ymd(ym)) %>%
  ggplot(aes(ym,cumsum(n))) +
  geom_line(color="blue") + #+geom_smooth()
  scale_x_date(date_breaks="1 year",date_labels = "%m/%y") +
  scale_y_continuous(breaks=seq(0,12000,1000),minor_breaks =seq(0,12000,1000))
```

