---
title: "Draw guitar fretboard"
output: github_document
---

```{r,echo=F}
knitr::opts_chunk$set(
  cache=T,
  collapse=T,
  comment="#>",
  dpi=96
)
```


```{r}
suppressWarnings(library(tidyverse))
library(purrr)
library(stringr)
library(rvest) # xml2 wrapper
```

```{r}
fs <- list.files(".","*html")
fs
```

```{r}
pkgs1 <- read_html(fs[1])
tab <- html_nodes(pkgs1, "table") %>% html_table(fill = TRUE)
pkgnames <- tab[[1]][1]$X1
pkgnames <- pkgnames[nchar(pkgnames)>0]
```


How many packages on CRAN? 

```{r}
pkgs <- available.packages()
rownames(pkgs) <- str_trim(rownames(pkgs),side="both")
length(pkgs)
pkgsD <- unique(rownames(pkgs))
length(pkgsD)
```

Most popular imports

```{r}
firstTok <- function(s) {
  x <- str_split(s," ")
  ifelse(length(x)>=1,first(x),NA_character_)
}
notSpace <- function(s) str_detect(s,"[^\\s]")

imps <- keep(map_chr(str_trim(unlist(str_split(pkgs[,"Imports"],",")),side="both"), firstTok), notSpace)
top200 <- as.tibble(sort(table(imps),decreasing = T)[1:200])
top200
```

```{r}
write_csv(top200,"top200.csv")
```

