---
title: "R Notebook"
output: html_notebook
---

```{r}
library(tidyverse)
library(purrr)
```



```{r}
semitone <- 2^(1/12)
middleC <- 440/(2^(9/12))
tones12 <- tibble(degree=1:13,
                  notes=c("C","C#",
                          "D","D#",
                          "E",
                          "F","F#", # 4ths is 6th note
                          "G","G#", # fifth is 8th note
                          "A","A#",
                          "B",
                          "C2"),
                  notesF=c("C","Db",
                          "D","Eb",
                          "E",
                          "F","Gb", # 4ths is 6th note
                          "G","Ab", # fifth is 8th note
                          "A","Bb",
                          "B",
                          "C2"),
                  freqMult=accumulate(degree[-13],~.x*semitone,.init=1),
                  freq=middleC*freqMult,
                  majorIdx=c(T,F,T,F,T,T,F,T,F,T,F,T,T),
                  minorIdx=c(T,F,T,T,F,T,F,T,T,F,T,F,T),
                  # 5ths
                  roots5ths=accumulate(0:11,~(.x+7)%%12,.init=0)+1,
                  notes5ths=notes[roots5ths],
                  freq5ths=accumulate(1:12,
                                      function(x,y) {
                                        f5<-x*freqMult[8]
                                        if_else(f5>2.01,f5/2,f5)
                                      },.init=1),
                  majorScale5ths=map_chr(roots5ths,
                                         ~paste0(notes[(.x+which(majorIdx)[-8]-2)%%12+1],
                                                 collapse=",")),
                  majorSharps5ths=map_chr(majorScale5ths,
                                          ~paste0(unlist(str_extract_all(.x,".#")),
                                                  collapse=",")),
                  majorSharps5ths=map_chr(majorScale5ths,
                                          ~paste0(unlist(str_extract_all(.x,".#")),
                                                  collapse=",")),

                  minorScale5ths=map_chr(roots5ths,   
                                         ~paste0(notes[(.x+which(minorIdx)[-8]-2)%%12+1],
                                                 collapse=",")),
                  minorSharps5ths=map_chr(minorScale5ths,
                                          ~paste0(unlist(str_extract_all(.x,".#")),
                                                  collapse=",")),
                  # 4ths
                  roots4ths=accumulate(0:11,~(.x+5)%%12,.init=0)+1,
                  notes4ths=notesF[roots4ths],
                  freq4ths=accumulate(1:12,
                                      function(x,y) {
                                        f5<-x*freqMult[6]
                                        if_else(f5>2.01,f5/2,f5)
                                      },.init=1),
                  majorScale4ths=map_chr(roots4ths,
                                         ~paste0(notesF[(.x+which(majorIdx)[-8]-2)%%12+1],
                                                 collapse=",")),
                  majorFlats4ths=map_chr(majorScale4ths,
                                          ~paste0(unlist(str_extract_all(.x,".b")),
                                                  collapse=",")),
                  minorScale4ths=map_chr(roots4ths,   
                                         ~paste0(notesF[(.x+which(minorIdx)[-8]-2)%%12+1],
                                                 collapse=",")),
                  minorFlats4ths=map_chr(minorScale4ths,
                                          ~paste0(unlist(str_extract_all(.x,".b")),
                                                  collapse=","))
                  )
View(tones12)
```

Draw fingerboard

```{r}
fretDist <- function(fretN) 1 / (2^(fretN/12))
fretDists <- fretDist(0:24)
fw2 <- .1
stringYs <- seq(fw2,-fw2,-2*fw2/5)
fretBoard <-
tibble(stringYs=stringYs) %>%
  ggplot() +
  # fingerboard (light wood)
  geom_rect(xmin=0,xmax=1,
            ymin=-1.1*fw2,ymax=1.1*fw2,
            color="#663300",fill="#663300") +
  # bridge (dark wood)
  geom_rect(xmin=-.02,xmax=0.02,
            ymin=-1.2*fw2,ymax=1.2*fw2,
            color="#330000",fill="#330000") +
  # nut (motherpearl)
  geom_rect(xmin=1,xmax=1.02,
            ymin=-1.2*fw2,ymax=1.2*fw2,
            color="#888888",fill="#888888") +
  # frets (black)
  geom_segment(aes(x=fretDists,xend=fretDists,
                   y=-1.1*fw2,yend=1.1*fw2),
             data=tibble(fretDists=fretDists)) +
  # marker dots (white)
  geom_point(aes(x=.5*(dotx+dotxN),y=0),
             data=tibble(dotx=fretDists[c(3,5,7,9)],
                         dotxN=fretDists[c(4,6,8,10)]),
             size=2,color="white") +
  geom_point(aes(x=dotx,y=doty),
             data=tibble(dotx=rep(.5*(fretDists[12]+fretDists[13]),2),
                         doty=c(-fw2/12,fw2/12)),
             size=2,color="white") +
  # strings
  geom_segment(aes(y=stringYs,yend=stringYs,
                   x=0,xend=1.02),color="grey") +
  # bridge pegs (blue)
  geom_point(aes(x=0,y=stringYs),size=4,color="blue") +
  coord_fixed(xlim=c(0,1.05),ylim=1.1*c(-fw2,fw2)) +
  labs(x="",y="",title="")
fretBoard
```

Where are the naturals

```{r}
tuning6 <- c("E","A","D","G","B","E")
# where in the notes vector
tuning6idx <- map_int(tuning6,~match(.x,tones12$notes[-13]))
naturalfretsCroot <- unlist(map((0:3)*12,~.x+which(tones12$majorIdx[-13])))-1

naturalfingerPos <-
map(tuning6idx-1,~as.integer(keep(naturalfretsCroot-.x,
                       function(y)y>0&y<=24)))
naturalfingerRel <-
map2(tuning6idx,naturalfingerPos,~(.x+.y-1)%%12+1)
naturalfingerNotes <- map(naturalfingerRel,~tones12$notes[.x])

fretDistsMid <- map2_dbl(fretDists[-length(fretDists)],
                         fretDists[-1],~.5*(.x+.y))
drawNotes <- function(p,s) {
  nfp <- naturalfingerPos[[s]]
  nfn <- naturalfingerNotes[[s]]
  df <- data_frame(nfp=nfp,
                    x=fretDistsMid[nfp],
                    y=stringYs[s],
                    nfn=nfn)
  p+
  geom_point(aes(x=x,y=y),size=7,color="black",data=df) +
  geom_text(aes(x=x,y=y,label=nfn),color="white",
            size=4,data=df)
}

#open notes
df0 <- data_frame(x=1.05,y=stringYs,nfn=tuning6)
# draw entire fretboard.
# loop doesn't work because drawNotes requires previous plot
reduce(1:6,~drawNotes(.x,.y),.init=fretBoard) +
  geom_point(aes(x=x,y=y),size=7,color="grey",data=df0) +
  geom_text(aes(x=x,y=y,label=nfn),color="black",
            size=4,data=df0)
```

